user_messages = {
    'Español': {
        'title': 'Bienvenido',
        'swap':'English',
        'main_menu_choice':'Escoja una opcion',
        'join_game':'Unirse a partida',
        'create_game':'Crear partida',
        'help':'Ayuda',
        'quit':'Salir',
        'help_skip':'La carta "skip" salta el turno del siguente jugador',
        'help_reverse':'La carta "reverse" cambia la direccion en que se toman los turnos',
        'help_+2':'La carta "+2" hace que el jugador siguiente jale 2 cartas y pierda turno',
        'help_+4':'La carta "+4" hace que el jugador siguiente jale 4 cartas, se cambie de color y pierda turno',
        'help_wild':'La carta "wild" cambia el siguiente color que se esta jugando',
        'help_uno':'Si un jugador tiene una carta se debe decir antes que los demas, sino jala 2 cartas',
        'help_stack':'Solo se puede subir cartas +2 a cartas +2 y +4 a +4 quien que no pueda seguir la cadena toma el total acomulado',
        '':'',
    },
    'English': {
        'title': 'Welcome',
        'swap': 'Español',
        'main_menu_choice':'Pick a choice',
        'join_game':'Join game',
        'create_game':'Create game',
        'help':'Help',
        'quit':'Quit',
        'help_skip': 'The next player is "skipped"',
        'help_reverse': 'Reverses the direction of play',
        'help_+2': 'The next player must draw 2 cards and lose a turn',
        'help_+4': 'Changes the current color plus the next player must draw 4 cards and lose a turn',
        'help_wild': 'Play this card to change the color to be matched',
        'help_uno': 'Challenge your opponent for not calling UNO. If they are caught, your opponent must draw two cards',
        'help_stack':'+2 cards and +4 can only be played on same type cards. The player who cant continue the stacking must draw the total',
        '':'',
        '':'',
    },
}
