#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 17, 2020 05:40:07 PM CST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import board_support

def board_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    board_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    board_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1099x718+450+160")
        top.minsize(1, 1)
        top.maxsize(3825, 1050)
        top.resizable(1, 1)
        top.title("Board")
        top.configure(background="#556B2F")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.045, rely=0.111, height=21, width=103)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#556B2F")
        self.Label1.configure(text='''Mi nombre:''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.062, rely=0.159, height=21, width=73)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="#556B2F")
        self.Label2.configure(text='''Turno de:''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.055, rely=0.613, height=41, width=204)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(text='''Jalar carta''')

        self.userName = tk.Label(top)
        self.userName.place(relx=0.146, rely=0.111, height=21, width=150)
        self.userName.configure(activebackground="#f9f9f9")
        self.userName.configure(text='''None''')

        self.turnName = tk.Label(top)
        self.turnName.place(relx=0.146, rely=0.153, height=21, width=150)
        self.turnName.configure(activebackground="#f9f9f9")
        self.turnName.configure(text='''...''')

        self.refreshBTN = tk.Button(top)
        self.refreshBTN.place(relx=0.055, rely=0.682, height=41, width=200)
        self.refreshBTN.configure(activebackground="#f9f9f9")
        self.refreshBTN.configure(text='''Refrescar''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.346, rely=0.251, relheight=0.486, relwidth=0.2)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#0000FF")

        self.Frame1_5 = tk.Frame(top)
        self.Frame1_5.place(relx=0.309, rely=0.237, relheight=0.486
                , relwidth=0.199)
        self.Frame1_5.configure(relief='groove')
        self.Frame1_5.configure(borderwidth="2")
        self.Frame1_5.configure(relief="groove")
        self.Frame1_5.configure(background="#FFFF00")

        self.Frame1_7 = tk.Frame(top)
        self.Frame1_7.place(relx=0.419, rely=0.376, relheight=0.486
                , relwidth=0.197)
        self.Frame1_7.configure(relief='groove')
        self.Frame1_7.configure(borderwidth="2")
        self.Frame1_7.configure(relief="groove")
        self.Frame1_7.configure(background="#FF0000")

        self.Frame1_8 = tk.Frame(top)
        self.Frame1_8.place(relx=0.282, rely=0.334, relheight=0.486
                , relwidth=0.2)
        self.Frame1_8.configure(relief='groove')
        self.Frame1_8.configure(borderwidth="2")
        self.Frame1_8.configure(relief="groove")
        self.Frame1_8.configure(background="#00FF00")

        self.Frame1_9 = tk.Frame(top)
        self.Frame1_9.place(relx=0.328, rely=0.292, relheight=0.486
                , relwidth=0.2)
        self.Frame1_9.configure(relief='groove')
        self.Frame1_9.configure(borderwidth="2")
        self.Frame1_9.configure(relief="groove")

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.819, rely=0.85, height=31, width=69)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(text='''Enviar''')

        self.Text1 = tk.Text(top)
        self.Text1.place(relx=0.701, rely=0.71, relheight=0.103, relwidth=0.288)
        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.configure(wrap="word")

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.701, rely=0.181, relheight=0.508
                , relwidth=0.288)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")

        self.playerList = tk.Frame(top)
        self.playerList.place(relx=0.045, rely=0.251, relheight=0.299
                , relwidth=0.197)
        self.playerList.configure(relief='groove')
        self.playerList.configure(borderwidth="2")
        self.playerList.configure(relief="groove")
        self.playerList.configure(background="#556B2F")

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.045, rely=0.223, height=21, width=80)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''Jugadores''')

        self.hand = tk.Frame(top)
        self.hand.place(relx=0.173, rely=0.877, relheight=0.091, relwidth=0.505)
        self.hand.configure(relief='groove')
        self.hand.configure(borderwidth="2")
        self.hand.configure(relief="groove")

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.91, rely=0.07, height=31, width=67)
        self.Button3.configure(activebackground="#f9f9f9")
        self.Button3.configure(background="#d82727")
        self.Button3.configure(text='''Salir''')

        self.Button4 = tk.Button(top)
        self.Button4.place(relx=0.701, rely=0.905, height=31, width=58)
        self.Button4.configure(text='''UNO''')







