#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 16, 2020 11:20:34 PM CST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Jugadores_support

def jugadores_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = waitingroom (root)
    Jugadores_support.init(root, top)

w = None
def create_waitingroom(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_waitingroom(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = waitingroom (w)
    Jugadores_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_waitingroom():
    global w
    w.destroy()
    w = None

class waitingroom:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+482+279")
        top.minsize(1, 1)
        top.maxsize(3825, 1050)
        top.resizable(1, 1)
        top.title("Esperando")
        top.configure(background="#556B2F")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.067, rely=0.089, height=21, width=159)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#556B2F")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''Lista de jugadores''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.267, rely=0.844, height=31, width=94)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(background="#89cff0")
        self.Button1.configure(text='''Comenzar''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.617, rely=0.844, height=31, width=85)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(background="#d9f4ed")
        self.Button2.configure(text='''Refescar''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.4, rely=0.133, height=21, width=110)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''Disponible''')

        self.Label2_9 = tk.Label(top)
        self.Label2_9.place(relx=0.067, rely=0.267, height=21, width=110)
        self.Label2_9.configure(activebackground="#f9f9f9")
        self.Label2_9.configure(text='''Disponible''')

        self.Label2_10 = tk.Label(top)
        self.Label2_10.place(relx=0.317, rely=0.356, height=21, width=110)
        self.Label2_10.configure(activebackground="#f9f9f9")
        self.Label2_10.configure(text='''Disponible''')

        self.Label2_11 = tk.Label(top)
        self.Label2_11.place(relx=0.7, rely=0.178, height=21, width=110)
        self.Label2_11.configure(activebackground="#f9f9f9")
        self.Label2_11.configure(text='''Disponible''')

        self.Label2_12 = tk.Label(top)
        self.Label2_12.place(relx=0.6, rely=0.289, height=21, width=110)
        self.Label2_12.configure(activebackground="#f9f9f9")
        self.Label2_12.configure(text='''Disponible''')

        self.Label2_13 = tk.Label(top)
        self.Label2_13.place(relx=0.017, rely=0.711, height=21, width=110)
        self.Label2_13.configure(activebackground="#f9f9f9")
        self.Label2_13.configure(text='''Disponible''')

        self.Label2_14 = tk.Label(top)
        self.Label2_14.place(relx=0.583, rely=0.489, height=21, width=110)
        self.Label2_14.configure(activebackground="#f9f9f9")
        self.Label2_14.configure(text='''Disponible''')

        self.Label2_15 = tk.Label(top)
        self.Label2_15.place(relx=0.35, rely=0.622, height=21, width=110)
        self.Label2_15.configure(activebackground="#f9f9f9")
        self.Label2_15.configure(text='''Disponible''')

        self.Label2_16 = tk.Label(top)
        self.Label2_16.place(relx=0.117, rely=0.467, height=21, width=110)
        self.Label2_16.configure(activebackground="#f9f9f9")
        self.Label2_16.configure(text='''Disponible''')

        self.Label2_17 = tk.Label(top)
        self.Label2_17.place(relx=0.75, rely=0.689, height=21, width=110)
        self.Label2_17.configure(activebackground="#f9f9f9")
        self.Label2_17.configure(text='''Disponible''')






